const getAllUni = (req, res) => {
  return res.status(200).json([
    {
      name: "دانشگاه آیت‌الله‌العظمی بروجردی",
      city: "بروجرد",
      establishedYear: "1385",
      NumberOfFaculties: "3",
      id: 1,
    },
    {
      name: "دانشگاه اراک",
      city: "اراک",
      establishedYear: "1350",
      NumberOfFaculties: "8",
      id: 2,
    },
    {
      name: "دانشگاه اردکان",
      city: "اردکان",
      establishedYear: "1388",
      NumberOfFaculties: "4",
      id: 3,
    },
    {
      name: "دانشگاه ارومیه",
      city: "ارومیه",
      establishedYear: "1344",
      NumberOfFaculties: "12",
      id: 4,
    },
    {
      name: "دانشگاه اصفهان",
      city: "اصفهان",
      establishedYear: "1325",
      NumberOfFaculties: "14",
      id: 5,
    },
    {
      name: "دانشگاه الزهرا",
      city: "تهران",
      establishedYear: "1343",
      NumberOfFaculties: "10",
      id: 6,
    },
    {
      name: "دانشگاه ایلام",
      city: "ایلام",
      establishedYear: "1355",
      NumberOfFaculties: "7",
      id: 7,
    },
    {
      name: "دانشگاه بجنورد",
      city: "بجنورد",
      establishedYear: "1384",
      NumberOfFaculties: "4",
      id: 8,
    },
    {
      name: "دانشگاه بزرگمهر",
      city: "قائن",
      establishedYear: "1393",
      NumberOfFaculties: "3",
      id: 9,
    },
    {
      name: "دانشگاه بناب",
      city: "بناب",
      establishedYear: "1375",
      NumberOfFaculties: "3",
      id: 10,
    },
    {
      name: "دانشگاه بوعلی سینا همدان",
      city: "همدان",
      establishedYear: "1353",
      NumberOfFaculties: "13",
      id: 11,
    },
    {
      name: "دانشگاه بیرجند",
      city: "بیرجند",
      establishedYear: "1354",
      NumberOfFaculties: "11",
      id: 12,
    },
    {
      name: "دانشگاه بین‌المللی امام خمینی",
      city: "قزوین",
      establishedYear: "1370",
      NumberOfFaculties: "6",
      id: 13,
    },
    {
      name: "دانشگاه تبریز",
      city: "تبریز",
      establishedYear: "1325",
      NumberOfFaculties: "20",
      id: 14,
    },
    {
      name: "دانشگاه تحصیلات تکمیلی صنعتی کرمان",
      city: "کرمان",
      establishedYear: "1386",
      NumberOfFaculties: "5",
      id: 15,
    },
    {
      name: "دانشگاه تحصیلات تکمیلی علوم پایه زنجان",
      city: "زنجان",
      establishedYear: "1371",
      NumberOfFaculties: "6",
      id: 16,
    },
    {
      name: "دانشگاه تخصصی فناوری‌های نوین آمل	",
      city: "آمل",
      establishedYear: "1392",
      NumberOfFaculties: "4",
      id: 17,
    },
    {
      name: "دانشگاه تربت حیدریه",
      city: "تربت حیدریه",
      establishedYear: "1384",
      NumberOfFaculties: "2",
      id: 18,
    },
    {
      name: "دانشگاه تربیت دبیر شهید رجایی",
      city: "تهران",
      establishedYear: "1357",
      NumberOfFaculties: "9",
      id: 19,
    },
    {
      name: "دانشگاه تربیت مدرس",
      city: "تهران",
      establishedYear: "1360",
      NumberOfFaculties: "17",
      id: 20,
    },
    {
      name: "دانشگاه تفرش",
      city: "تفرش",
      establishedYear: "1367",
      NumberOfFaculties: "8",
      id: 21,
    },
    {
      name: "دانشگاه تهران",
      city: "تهران",
      establishedYear: "1313",
      NumberOfFaculties: "24",
      id: 22,
    },
    {
      name: "دانشگاه جیرفت",
      city: "جیرفت",
      establishedYear: "1368",
      NumberOfFaculties: "5",
      id: 23,
    },
    {
      name: "دانشگاه جهرم",
      city: "جهرم",
      establishedYear: "1352",
      NumberOfFaculties: "4",
      id: 24,
    },
    {
      name: "دانشگاه حضرت نرجس رفسنجان",
      city: "رفسنجان",
      establishedYear: "1391",
      NumberOfFaculties: "1",
      id: 25,
    },
  ]);
};

//*>----------- module export

module.exports = { getAllUni };
