const getAllUni = (req, res) => {
  return res.status(200).json([
    {
      name: "دانشگاه آیت‌الله‌العظمی بروجردی",
      city: "بروجرد",
      establishedYear: "1385",
      NumberOfFaculties: "3",
      id: 1,
    },
    {
      name: "دانشگاه اراک",
      city: "اراک",
      establishedYear: "1350",
      NumberOfFaculties: "8",
      id: 2,
    },
    {
      name: "دانشگاه اردکان",
      city: "اردکان",
      establishedYear: "1388",
      NumberOfFaculties: "4",
      id: 3,
    },
    {
      name: "دانشگاه ارومیه",
      city: "ارومیه",
      establishedYear: "1344",
      NumberOfFaculties: "12",
      id: 4,
    },
    {
      name: "دانشگاه اصفهان",
      city: "اصفهان",
      establishedYear: "1325",
      NumberOfFaculties: "14",
      id: 5,
    },
    {
      name: "دانشگاه الزهرا",
      city: "تهران",
      establishedYear: "1343",
      NumberOfFaculties: "10",
      id: 6,
    },
    {
      name: "دانشگاه ایلام",
      city: "ایلام",
      establishedYear: "1355",
      NumberOfFaculties: "7",
      id: 7,
    },
    {
      name: "دانشگاه بجنورد",
      city: "بجنورد",
      establishedYear: "1384",
      NumberOfFaculties: "4",
      id: 8,
    },
    {
      name: "دانشگاه بزرگمهر",
      city: "قائن",
      establishedYear: "1393",
      NumberOfFaculties: "3",
      id: 9,
    },
    {
      name: "دانشگاه بناب",
      city: "بناب",
      establishedYear: "1375",
      NumberOfFaculties: "3",
      id: 10,
    },
    {
      name: "دانشگاه بوعلی سینا همدان",
      city: "همدان",
      establishedYear: "1353",
      NumberOfFaculties: "13",
      id: 11,
    },
    {
      name: "دانشگاه بیرجند",
      city: "بیرجند",
      establishedYear: "1354",
      NumberOfFaculties: "11",
      id: 12,
    },
    {
      name: "دانشگاه بین‌المللی امام خمینی",
      city: "قزوین",
      establishedYear: "1370",
      NumberOfFaculties: "6",
      id: 13,
    },
    {
      name: "دانشگاه تبریز",
      city: "تبریز",
      establishedYear: "1325",
      NumberOfFaculties: "20",
      id: 14,
    },
    {
      name: "دانشگاه تحصیلات تکمیلی صنعتی کرمان",
      city: "کرمان",
      establishedYear: "1386",
      NumberOfFaculties: "5",
      id: 15,
    },
    {
      name: "دانشگاه تحصیلات تکمیلی علوم پایه زنجان",
      city: "زنجان",
      establishedYear: "1371",
      NumberOfFaculties: "6",
      id: 16,
    },
    {
      name: "دانشگاه تخصصی فناوری‌های نوین آمل",
      city: "آمل",
      establishedYear: "1392",
      NumberOfFaculties: "4",
      id: 17,
    },
    {
      name: "دانشگاه تربت حیدریه",
      city: "تربت حیدریه",
      establishedYear: "1384",
      NumberOfFaculties: "2",
      id: 18,
    },
    {
      name: "دانشگاه تربیت دبیر شهید رجایی",
      city: "تهران",
      establishedYear: "1357",
      NumberOfFaculties: "9",
      id: 19,
    },
    {
      name: "دانشگاه تربیت مدرس",
      city: "تهران",
      establishedYear: "1360",
      NumberOfFaculties: "17",
      id: 20,
    },
    {
      name: "دانشگاه تفرش",
      city: "تفرش",
      establishedYear: "1367",
      NumberOfFaculties: "8",
      id: 21,
    },
    {
      name: "دانشگاه تهران",
      city: "تهران",
      establishedYear: "1313",
      NumberOfFaculties: "24",
      id: 22,
    },
    {
      name: "دانشگاه جیرفت",
      city: "جیرفت",
      establishedYear: "1368",
      NumberOfFaculties: "5",
      id: 23,
    },
    {
      name: "دانشگاه جهرم",
      city: "جهرم",
      establishedYear: "1352",
      NumberOfFaculties: "4",
      id: 24,
    },
    {
      name: "دانشگاه حضرت نرجس رفسنجان",
      city: "رفسنجان",
      establishedYear: "1391",
      NumberOfFaculties: "1",
      id: 25,
    },
    {
      name: "دانشگاه حکیم سبزواری",
      city: "سبزوار",
      establishedYear: "1366",
      NumberOfFaculties: "10",
      id: 26,
    },
    {
      name: "دانشگاه خلیج فارس بوشهر",
      city: "بوشهر",
      establishedYear: "1371",
      NumberOfFaculties: "8",
      id: 27,
    },
    {
      name: "دانشگاه خوارزمی",
      city: "تهران",
      establishedYear: "1297",
      NumberOfFaculties: "14",
      id: 28,
    },
    {
      name: "دانشگاه دامغان",
      city: "دامغان",
      establishedYear: "1368",
      NumberOfFaculties: "8",
      id: 29,
    },
    {
      name: "دانشگاه حضرت معصومه",
      city: "قم",
      establishedYear: "1386",
      NumberOfFaculties: "1",
      id: 30,
    },
    {
      name: "دانشگاه دریانوردی و علوم دریایی چابهار	",
      city: "چابهار",
      establishedYear: "1355",
      NumberOfFaculties: "3",
      id: 31,
    },
    {
      name: "دانشگاه رازی کرمانشاه",
      city: "کرمانشاه",
      establishedYear: "1351",
      NumberOfFaculties: "13",
      id: 32,
    },
    {
      name: "دانشگاه زابل",
      city: "زابل",
      establishedYear: "1357",
      NumberOfFaculties: "9",
      id: 33,
    },
    {
      name: "دانشگاه زنجان",
      city: "زنجان",
      establishedYear: "1353",
      NumberOfFaculties: "5",
      id: 34,
    },
    {
      name: "دانشگاه سلمان فارسی کازرون",
      city: "کازرون",
      establishedYear: "1372",
      NumberOfFaculties: "4",
      id: 35,
    },
    {
      name: "دانشگاه سید جمال‌الدین اسدآبادی",
      city: "اسدآباد",
      establishedYear: "1390",
      NumberOfFaculties: "4",
      id: 36,
    },
    {
      name: "دانشگاه سمنان",
      city: "سمنان",
      establishedYear: "1353",
      NumberOfFaculties: "24",
      id: 37,
    },
    {
      name: "دانشگاه سیستان و بلوچستان",
      city: "زاهدان",
      establishedYear: "1353",
      NumberOfFaculties: "12",
      id: 38,
    },
    {
      name: "دانشگاه شاهد",
      city: "تهران",
      establishedYear: "1369",
      NumberOfFaculties: "5",
      id: 39,
    },
    {
      name: "دانشگاه بین‌المللی مذاهب اسلامی",
      city: "تهران",
      establishedYear: "1371",
      NumberOfFaculties: "3",
      id: 40,
    },
    {
      name: "دانشگاه شهرکرد",
      city: "شهرکرد",
      establishedYear: "1356",
      NumberOfFaculties: "8",
      id: 41,
    },
    {
      name: "دانشگاه شهید باهنر کرمان",
      city: "کرمان",
      establishedYear: "1351",
      NumberOfFaculties: "11",
      id: 42,
    },
    {
      name: "دانشگاه شهید بهشتی",
      city: "تهران",
      establishedYear: "1338",
      NumberOfFaculties: "19",
      id: 43,
    },
    {
      name: "دانشگاه شهید چمران اهواز",
      city: "اهواز",
      establishedYear: "1334",
      NumberOfFaculties: "15",
      id: 44,
    },
    {
      name: "دانشگاه شهید مدنی آذربایجان",
      city: "تبریز",
      establishedYear: "1364",
      NumberOfFaculties: "7",
      id: 45,
    },
    {
      name: "دانشگاه شیراز",
      city: "شیراز",
      establishedYear: "1325",
      NumberOfFaculties: "15",
      id: 46,
    },
    {
      name: "دانشگاه صنعتی اراک",
      city: "اراک",
      establishedYear: "1367",
      NumberOfFaculties: "4",
      id: 47,
    },
    {
      name: "دانشگاه صنعتی ارومیه",
      city: "ارومیه",
      establishedYear: "1384",
      NumberOfFaculties: "3",
      id: 48,
    },
    {
      name: "دانشگاه صنعتی اصفهان",
      city: "اصفهان",
      establishedYear: "1356",
      NumberOfFaculties: "14",
      id: 49,
    },
    {
      name: "دانشگاه صنعتی امیرکبیر",
      city: "تهران",
      establishedYear: "1337",
      NumberOfFaculties: "20",
      id: 50,
    },

    {
      name: "دانشگاه صنعتی بیرجند",
      city: "بیرجند",
      establishedYear: "1386",
      NumberOfFaculties: "3",
      id: 51,
    },
    {
      name: "دانشگاه صنعتی جندی‌شاپور",
      city: "دزفول",
      establishedYear: "1351",
      NumberOfFaculties: "5",
      id: 52,
    },
    {
      name: "دانشگاه صنعتی خاتم‌الانبیا",
      city: "بهبهان",
      establishedYear: "1380",
      NumberOfFaculties: "3",
      id: 53,
    },
    {
      name: "دانشگاه صنعتی خواجه نصیرالدین طوسی",
      city: "تهران",
      establishedYear: "1307",
      NumberOfFaculties: "11",
      id: 54,
    },
    {
      name: "دانشگاه صنعتی سهند",
      city: "سهند",
      establishedYear: "1369",
      NumberOfFaculties: "7",
      id: 55,
    },
    {
      name: "دانشگاه صنعتی سیرجان",
      city: "سیرجان",
      establishedYear: "1371",
      NumberOfFaculties: "6",
      id: 56,
    },
    {
      name: "دانشگاه صنعتی شاهرود",
      city: "شاهرود	",
      establishedYear: "1352",
      NumberOfFaculties: "3",
      id: 57,
    },
    {
      name: "دانشگاه صنعتی شریف",
      city: "تهران",
      establishedYear: "1344",
      NumberOfFaculties: "15",
      id: 58,
    },
    {
      name: "دانشگاه صنعتی شهدای هویزه",
      city: "سوسنگرد",
      establishedYear: "1388",
      NumberOfFaculties: "2",
      id: 59,
    },
    {
      name: "دانشگاه صنعتی شیراز",
      city: "شیراز",
      establishedYear: "1343",
      NumberOfFaculties: "10",
      id: 60,
    },
    {
      name: "دانشگاه صنعتی قم",
      city: "قم",
      establishedYear: "1387",
      NumberOfFaculties: "3",
      id: 61,
    },
    {
      name: "دانشگاه صنعتی قوچان",
      city: "قوچان",
      establishedYear: "1385",
      NumberOfFaculties: "1",
      id: 62,
    },
    {
      name: "دانشگاه صنعتی کرمانشاه",
      city: "کرمانشاه",
      establishedYear: "1386",
      NumberOfFaculties: "4",
      id: 63,
    },
    {
      name: "دانشگاه صنعتی نوشیروانی بابل",
      city: "بابل",
      establishedYear: "1348",
      NumberOfFaculties: "6",
      id: 64,
    },
    {
      name: "دانشگاه صنعتی همدان",
      city: "همدان",
      establishedYear: "1383",
      NumberOfFaculties: "3",
      id: 65,
    },
    {
      name: "دانشگاه علامه طباطبایی",
      city: "تهران",
      establishedYear: "1363",
      NumberOfFaculties: "13",
      id: 66,
    },
    {
      name: "دانشگاه علم و صنعت ایران",
      city: "تهران",
      establishedYear: "1341",
      NumberOfFaculties: "15",
      id: 67,
    },
    {
      name: "دانشگاه علم و فناوری مازندران",
      city: "بهشهر",
      establishedYear: "1373",
      NumberOfFaculties: "3",
      id: 68,
    },
    {
      name: "دانشگاه علوم و فنون دریایی خرمشهر",
      city: "خرمشهر",
      establishedYear: "1355",
      NumberOfFaculties: "4",
      id: 69,
    },
    {
      name: "دانشگاه علوم کشاورزی و منابع طبیعی ساری",
      city: "ساری",
      establishedYear: "1353",
      NumberOfFaculties: "8",
      id: 70,
    },
    {
      name: "دانشگاه علوم کشاورزی و منابع طبیعی گرگان",
      city: "گرگان",
      establishedYear: "1336",
      NumberOfFaculties: "9",
      id: 71,
    },
    {
      name: "دانشگاه فردوسی مشهد",
      city: "مشهد",
      establishedYear: "1328",
      NumberOfFaculties: "13",
      id: 72,
    },
    {
      name: "دانشگاه فرزانگان سمنان",
      city: "سمنان",
      establishedYear: "1392",
      NumberOfFaculties: "1",
      id: 73,
    },
    {
      name: "دانشگاه فسا",
      city: "فس",
      establishedYear: "1385",
      NumberOfFaculties: "4",
      id: 74,
    },
    {
      name: "دانشگاه قم",
      city: "قم",
      establishedYear: "1358",
      NumberOfFaculties: "6",
      id: 75,
    },
    {
      name: "دانشگاه کاشان",
      city: "کاشان",
      establishedYear: "1352",
      NumberOfFaculties: "11",
      id: 76,
    },
    {
      name: "دانشگاه کردستان",
      city: "سنندج",
      establishedYear: "1353",
      NumberOfFaculties: "8",
      id: 77,
    },
    {
      name: "دانشگاه کشاورزی و منابع طبیعی رامین",
      city: "ملاثانی",
      establishedYear: "1334",
      NumberOfFaculties: "4",
      id: 78,
    },
    {
      name: "دانشگاه کوثر بجنورد",
      city: "بجنورد",
      establishedYear: "1391",
      NumberOfFaculties: "2",
      id: 79,
    },
    {
      name: "دانشگاه گرمسار",
      city: "گرمسار",
      establishedYear: "1390",
      NumberOfFaculties: "1",
      id: 80,
    },
    {
      name: "دانشگاه گلستان",
      city: "گرگان",
      establishedYear: "1387",
      NumberOfFaculties: "4",
      id: 81,
    },
    {
      name: "دانشگاه گنبد کاووس",
      city: "گنبد کاووس",
      establishedYear: "1388",
      NumberOfFaculties: "5",
      id: 82,
    },
    {
      name: "دانشگاه گیلان",
      city: "رشت",
      establishedYear: "1353",
      NumberOfFaculties: "10",
      id: 83,
    },
    {
      name: "دانشگاه لرستان",
      city: "خرم‌آباد",
      establishedYear: "1356",
      NumberOfFaculties: "6",
      id: 84,
    },
    {
      name: "دانشگاه مازندران",
      city: "بابلسر",
      establishedYear: "1358",
      NumberOfFaculties: "13",
      id: 85,
    },
    {
      name: "دانشگاه محقق اردبیلی",
      city: "اردبیل",
      establishedYear: "1357",
      NumberOfFaculties: "8",
      id: 86,
    },
    {
      name: "دانشگاه مراغه",
      city: "مراغه",
      establishedYear: "1366",
      NumberOfFaculties: "4",
      id: 87,
    },
    {
      name: "دانشگاه ملایر",
      city: "ملایر",
      establishedYear: "1370",
      NumberOfFaculties: "7",
      id: 88,
    },
    {
      name: "دانشگاه مهندسی علوم و فناوری‌های نوین گلبهار",
      city: "گلبهار",
      establishedYear: "1390",
      NumberOfFaculties: "3",
      id: 89,
    },
    {
      name: "دانشگاه مهندسی علوم و فناوری‌های نوین گلبهار",
      city: "گلبهار",
      establishedYear: "1390",
      NumberOfFaculties: "3",
      id: 89,
    },
    {
      name: "دانشگاه میبد",
      city: "میبد",
      establishedYear: "1374",
      NumberOfFaculties: "3",
      id: 90,
    },
    {
      name: "دانشگاه نیشابور",
      city: "نیشابور",
      establishedYear: "1373",
      NumberOfFaculties: "5",
      id: 91,
    },
    {
      name: "دانشگاه ولایت ایرانشهر",
      city: "ایرانشهر",
      establishedYear: "1372",
      NumberOfFaculties: "5",
      id: 92,
    },
    {
      name: "دانشگاه ولی‌عصر رفسنجان",
      city: "رفسنجان",
      establishedYear: "1369",
      NumberOfFaculties: "7",
      id: 93,
    },
    {
      name: "دانشگاه هرمزگان",
      city: "بندرعباس",
      establishedYear: "1370",
      NumberOfFaculties: "6",
      id: 94,
    },
    {
      name: "دانشگاه هنر اسلامی تبریز",
      city: "تبریز",
      establishedYear: "1378",
      NumberOfFaculties: "8",
      id: 95,
    },
    {
      name: "دانشگاه هنر اصفهان",
      city: "اصفهان",
      establishedYear: "1355",
      NumberOfFaculties: "5",
      id: 96,
    },
    {
      name: "دانشگاه هنر تهران",
      city: "تهران",
      establishedYear: "1339",
      NumberOfFaculties: "7",
      id: 97,
    },
    {
      name: "دانشگاه هنر شیراز",
      city: "شیراز",
      establishedYear: "1390",
      NumberOfFaculties: "5",
      id: 98,
    },
    {
      name: "دانشگاه یاسوج",
      city: "یاسوج",
      establishedYear: "1362",
      NumberOfFaculties: "5",
      id: 99,
    },
    {
      name: "دانشگاه یزد",
      city: "یزد",
      establishedYear: "1366",
      NumberOfFaculties: "14",
      id: 100,
    },
    {
      name: "دانشگاه علوم توانبخشی و سلامت اجتماعی",
      city: "تهران",
      establishedYear: "1371",
      NumberOfFaculties: "3",
      id: 101,
    },
    {
      name: "دانشگاه علوم پزشکی آبادان",
      city: "آبادان",
      establishedYear: "1353",
      NumberOfFaculties: "2",
      id: 102,
    },
    {
      name: "دانشگاه علوم پزشکی اراک",
      city: "اراک",
      establishedYear: "1365",
      NumberOfFaculties: "7",
      id: 103,
    },
    {
      name: "دانشگاه علوم پزشکی ارتش",
      city: "تهران",
      establishedYear: "1350",
      NumberOfFaculties: "5",
      id: 104,
    },
    {
      name: "دانشگاه علوم پزشکی اردبیل",
      city: "اردبیل",
      establishedYear: "1372",
      NumberOfFaculties: "9",
      id: 105,
    },
    {
      name: "دانشگاه علوم پزشکی ارومیه",
      city: "ارومیه",
      establishedYear: "1356",
      NumberOfFaculties: "12",
      id: 106,
    },
    {
      name: "دانشکده علوم پزشکی اسدآباد",
      city: "اسدآباد",
      establishedYear: "1390",
      NumberOfFaculties: "1",
      id: 107,
    },
    {
      name: "دانشکده علوم پزشکی اسفراین",
      city: "اسفراین",
      establishedYear: "1390",
      NumberOfFaculties: "1",
      id: 108,
    },
    {
      name: "دانشگاه علوم پزشکی اصفهان",
      city: "اصفهان",
      establishedYear: "1325",
      NumberOfFaculties: "11",
      id: 109,
    },
    {
      name: "دانشگاه علوم پزشکی البرز",
      city: "کرج",
      establishedYear: "1386",
      NumberOfFaculties: "7",
      id: 110,
    },
    {
      name: "دانشگاه علوم پزشکی ایران",
      city: "تهران",
      establishedYear: "1352",
      NumberOfFaculties: "10",
      id: 111,
    },
    {
      name: "دانشگاه علوم پزشکی ایرانشهر",
      city: "ایرانشهر",
      establishedYear: "1372",
      NumberOfFaculties: "5",
      id: 112,
    },
    {
      name: "دانشگاه علوم پزشکی ایلام",
      city: "ایلام",
      establishedYear: "1369",
      NumberOfFaculties: "5",
      id: 113,
    },
    {
      name: "دانشگاه علوم پزشکی بابل",
      city: "بابل",
      establishedYear: "1362",
      NumberOfFaculties: "8",
      id: 114,
    },
    {
      name: "دانشگاه علوم پزشکی بقیةالله",
      city: "تهران",
      establishedYear: "1364",
      NumberOfFaculties: "4",
      id: 115,
    },
    {
      name: "دانشگاه علوم پزشکی بم",
      city: "بم",
      establishedYear: "1370",
      NumberOfFaculties: "34",
      id: 116,
    },
    {
      name: "دانشگاه علوم پزشکی بوشهر",
      city: "بوشهر",
      establishedYear: "1362",
      NumberOfFaculties: "5",
      id: 117,
    },
    {
      name: "دانشکده علوم پزشکی بهبهان",
      city: "بهبهان",
      establishedYear: "1370",
      NumberOfFaculties: "1",
      id: 118,
    },
    {
      name: "دانشگاه علوم پزشکی بیرجند",
      city: "بیرجند",
      establishedYear: "1364",
      NumberOfFaculties: "10",
      id: 119,
    },
    {
      name: "دانشکده علوم پزشکی بروجن",
      city: "بروجن",
      establishedYear: "1371",
      NumberOfFaculties: "2",
      id: 120,
    },
    {
      name: "دانشگاه علوم پزشکی تبریز",
      city: "تبریز",
      establishedYear: "1325",
      NumberOfFaculties: "12",
      id: 121,
    },
    {
      name: "دانشکده علوم پزشکی تربت جام",
      city: "تربت جام",
      establishedYear: "1390",
      NumberOfFaculties: "1",
      id: 122,
    },
    {
      name: "دانشگاه علوم پزشکی تربت حیدریه",
      city: "تربت حیدریه",
      establishedYear: "1372",
      NumberOfFaculties: "3",
      id: 123,
    },
    {
      name: "دانشگاه علوم پزشکی تهران",
      city: "تهران",
      establishedYear: "1313",
      NumberOfFaculties: "12",
      id: 124,
    },
    {
      name: "دانشگاه علوم پزشکی جندی‌شاپور",
      city: "اهواز",
      establishedYear: "1336",
      NumberOfFaculties: "10",
      id: 125,
    },
    {
      name: "دانشگاه علوم پزشکی جهرم",
      city: "جهرم",
      establishedYear: "1356",
      NumberOfFaculties: "3",
      id: 126,
    },
    {
      name: "دانشگاه علوم پزشکی جیرفت",
      city: "جیرفت",
      establishedYear: "1367",
      NumberOfFaculties: "4",
      id: 127,
    },
    {
      name: "دانشگاه علوم پزشکی خراسان شمالی",
      city: "بجنورد",
      establishedYear: "1370",
      NumberOfFaculties: "6",
      id: 128,
    },
    {
      name: "دانشکده علوم پزشکی خلخال",
      city: "خلخال",
      establishedYear: "1372",
      NumberOfFaculties: "1",
      id: 129,
    },
    {
      name: "دانشکده علوم پزشکی خمین",
      city: "خمین	",
      establishedYear: "1371",
      NumberOfFaculties: "1",
      id: 130,
    },
    {
      name: "دانشکده علوم پزشکی خوی",
      city: "خوی",
      establishedYear: "1371",
      NumberOfFaculties: "1",
      id: 131,
    },
    {
      name: "دانشگاه علوم پزشکی دزفول",
      city: "رفسنجان",
      establishedYear: "1386",
      NumberOfFaculties: "5",
      id: 132,
    },
    {
      name: "دانشگاه علوم پزشکی زابل",
      city: "زابل",
      establishedYear: "1370",
      NumberOfFaculties: "5",
      id: 133,
    },
    {
      name: "دانشگاه علوم پزشکی زاهدان",
      city: "زاهدان",
      establishedYear: "1365",
      NumberOfFaculties: "7",
      id: 134,
    },
    {
      name: "دانشگاه علوم پزشکی زنجان",
      city: "زنجان",
      establishedYear: "1366",
      NumberOfFaculties: "8",
      id: 135,
    },
    {
      name: "دانشکده علوم پزشکی ساوه",
      city: "ساوه",
      establishedYear: "1376",
      NumberOfFaculties: "1",
      id: 136,
    },
    {
      name: "دانشگاه علوم پزشکی سبزوار",
      city: "سبزوار",
      establishedYear: "1365",
      NumberOfFaculties: "5",
      id: 137,
    },
    {
      name: "دانشکده علوم پزشکی سراب",
      city: "سراب",
      establishedYear: "1392",
      NumberOfFaculties: "1",
      id: 138,
    },
  ]);
};

//*>----------- module export

module.exports = { getAllUni };
